### ISSUE TITLE
Master build fails

### ISSUE THREAD

**Issue by jannikluhn** [trustlines-network/ethstats-client#12]
Currently, the master build is failing in the deployment step:  https://circleci.com/gh/trustlines-protocol/ethstats-client/17

Error message:

```
#!/bin/bash -eo pipefail
du -hc ~/images/*
docker load --input ~/images/$LOCAL_IMAGE.tar
docker image ls

du: cannot access '/home/circleci/images/*': No such file or directory
0	total
Exited with code 1
```

Most likely, the reason is that we try to upload the image before the build has been finished. This is fixed in #11

**Comment by andfletcher** [comment]
Done. Closed.
